# Foundation config (we'll expand later)
data:
  save-interval-seconds: 120

guilds:
  inactivity-autodisbands-days: 30
  impeach-min-members: 10

claims:
  leader-start-chunks: 4
  power-max-per-player: 15
  member-chunks-per-10-power: 1
  chunk-cost: 75

economy:
  enabled: true
  vault-required: true

invites:
  expire-seconds: 300

alignment:
  warn-interval-minutes: 30
  out-of-alignment-grace-hours: 48

  messages:
    honorable:
      login: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
      repeat: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
    neutral:
      login: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
      repeat: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
    dark:
      login: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
      repeat: "&7[&aGuild&7] &cYou are out of favor with your guild. You have &e%timeleft% &cto restore your %restore%&c."
